# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
        ALI_OSS_ACCESS_KEY_ID: ${{ secrets.ALI_OSS_ACCESS_KEY_ID }}
        ALI_OSS_ACCESS_KEY_SECRET: ${{ secrets.ALI_OSS_ACCESS_KEY_SECRET }}
        ALI_OSS_BUCKET: ${{ secrets.ALI_OSS_BUCKET }}
        ALI_OSS_REGION: ${{ secrets.ALI_OSS_REGION }}

    - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        author_name: Bowen7

        # The email of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_email: 771797746@qq.com

        # The message for the commit
        # Default: 'Commit from GitHub Actions'
        message: 'bot: update readme and hash'
      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged

